version: '3'

services:
  api:
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
#
#  db:
#    image: postgres:14.1-alpine
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - PGDATA=/data/postgres
#    volumes:
#       - postgres-db:/data/postgres
#    ports:
#      - '5432:5432'

  client:
    build: client
    command: ["npm", "start"]

    volumes:
      - ./client:/frontend
#      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

#volumes:
#  postgres-db:
#    driver: local
#  node-modules: