version: '3'

services:
  api:
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
  client:
    build: client
    command: ["npm", "start"]

    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=production # development
      - PORT=80
      - PG_HOST=XXX
      - PG_PASSWORD=XXX
    ports:
      - '80:80'
    depends_on:
      - api
volumes:
  node-modules: